### ISSUE TITLE
关于 java链接数据库 以及数据库版本安装以及city.sql文件的导入问题 key我申请好了

### ISSUE THREAD

**Issue by TuqicZ** [w-Bro/weather-forecast#1]
### 大佬可以 发一下mysql5.7 的安装包嘛 我java一直连不上数据库 city.sql文件能把数据库的表也是导不进 QAQ

**Comment by w-Bro** [comment]
> ### 大佬可以 发一下mysql5.7 的安装包嘛 我java一直连不上数据库 city.sql文件能把数据库的表也是导不进 QAQ

emm，mysql官网下载就可以，没什么特别的，连不上先看一下有没有报错以及是否尝试过用一些可视化工具(比如navicat)进行连接？包括sql文件导不进去的报错信息之类的贴出来我可能才帮得上你。代码方面因为是我大二还是大三的时候写的，太久远而且API方面应该改动也很大，能不能帮上你就不好说了。

**Comment by w-Bro** [comment]
> ### 大佬可以 发一下mysql5.7 的安装包嘛 我java一直连不上数据库 city.sql文件能把数据库的表也是导不进 QAQ

emm，mysql官网下载就可以，没什么特别的，连不上先看一下有没有报错以及是否尝试过用一些可视化工具(比如navicat)进行连接？包括sql文件导不进去的报错信息之类的贴出来我可能才帮得上你。代码方面因为是我大二还是大三的时候写的，太久远而且API方面应该改动也很大，能不能帮上你就不好说了。

**Comment by TuqicZ** [comment]
感谢回复 我后来转做学生管理系统的课设了今天下午答辩 不过 还是得 蟹蟹学长的回复 比心&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "w-Bro/weather-forecast"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月28日(星期二) 上午9:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [w-Bro/weather-forecast] 关于 java链接数据库 以及数据库版本安装以及city.sql文件的导入问题 key我申请好了 (Issue #1)





  
大佬可以 发一下mysql5.7 的安装包嘛 我java一直连不上数据库 city.sql文件能把数据库的表也是导不进 QAQ
  
emm，mysql官网下载就可以，没什么特别的，连不上先看一下有没有报错以及是否尝试过用一些可视化工具(比如navicat)进行连接？包括sql文件导不进去的报错信息之类的贴出来我可能才帮得上你。代码方面因为是我大二还是大三的时候写的，太久远而且API方面应该改动也很大，能不能帮上你就不好说了。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by w-Bro** [comment]
好的好的，最近没什么时间上来看，所以回复晚了。
